version: "3.8"

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: auth_db
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # Environment Configuration
      - ENVIRONMENT=development  # development or production
      - DEBUG=True               # True for development, False for production
      
      # URL Configuration
      - FRONTEND_URL=http://localhost:5173      # URL where your frontend is running
      - BACKEND_URL=http://localhost:5000       # URL where your backend is running
      - DOMAIN=your-domain.com                  # Your production domain (for production only)
      - FRONTEND_DOMAIN=https://your-domain.com # Your production frontend URL (for production only)
      - BACKEND_DOMAIN=https://api.your-domain.com # Your production backend URL (for production only)
      
      # CORS Configuration
      - CORS_ORIGINS=http://localhost:5173      # Comma-separated list of allowed origins
      
      # Security
      - SECRET_KEY=your-super-secret-key-change-this-in-production  # CHANGE THIS TO A SECURE RANDOM STRING
      
      # Database Configuration
      - DB_HOST=db               # Database host (use 'db' for Docker setup)
      - DB_PORT=3306             # Database port
      - DB_USER=root             # Database username
      - DB_PASSWORD=example      # Database password (CHANGE THIS)
      - DB_NAME=auth_db          # Database name
      
      # Email Configuration (Zoho Mail example - update for your provider)
      - MAIL_SERVER=smtp.zoho.com           # SMTP server for your email provider
      - MAIL_PORT=465                       # SMTP port (465 for SSL, 587 for TLS)
      - MAIL_USE_TLS=False                  # True for TLS, False for SSL
      - MAIL_USERNAME=your-email@domain.com # Your email address
      - MAIL_PASSWORD=your-email-password   # Your email password or app password
      - MAIL_DEFAULT_SENDER=your-email@domain.com # Default sender email address
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
    ports:
      - "5173:5173"             # Port mapping for frontend (host:container)
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      # API Configuration
      - VITE_API_BASE_URL=http://localhost:5000  # Backend API URL
      - VITE_API_URL=http://localhost:5000       # Backend API URL (legacy support)
      
      # App Configuration
      - VITE_APP_NAME=Job Tracker               # Application name
      - VITE_VERSION=1.0.0                      # Application version

volumes:
  mariadb_data:

# Configuration Notes:
# 
# 1. Copy this file to docker-compose.yml: cp docker-compose-example.yml docker-compose.yml
# 2. Update all placeholder values with your actual configuration
# 3. IMPORTANT: Change the SECRET_KEY to a secure random string
# 4. IMPORTANT: Change the database password (DB_PASSWORD and MARIADB_ROOT_PASSWORD)
# 5. Update email configuration with your email provider settings
# 6. For production, update DOMAIN, FRONTEND_DOMAIN, and BACKEND_DOMAIN
# 7. Update CORS_ORIGINS to include your production frontend URL
#
# Common Email Provider Settings:
# 
# Gmail:
# - MAIL_SERVER=smtp.gmail.com
# - MAIL_PORT=587
# - MAIL_USE_TLS=True
# - Use an App Password (not your regular password)
#
# Outlook/Hotmail:
# - MAIL_SERVER=smtp-mail.outlook.com
# - MAIL_PORT=587
# - MAIL_USE_TLS=True
#
# Yahoo:
# - MAIL_SERVER=smtp.mail.yahoo.com
# - MAIL_PORT=587
# - MAIL_USE_TLS=True
#
# Zoho:
# - MAIL_SERVER=smtp.zoho.com
# - MAIL_PORT=465 (SSL) or 587 (TLS)
# - MAIL_USE_TLS=False (for SSL) or True (for TLS)
