name: Deploy App
on:
  push:
    branches:
      - main
      - release/*
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull latest changes
        run: git pull
      - name: Shut down current containers
        run: docker-compose down || true
      - name: Build and start containers
        run: docker-compose up -d --build
